DROP SEQUENCE RESERVEDSEAT_SEQ;
DROP TABLE RESERVEDSEAT;

CREATE SEQUENCE RESERVEDSEAT_SEQ;
CREATE TABLE RESERVEDSEAT(
	RESERVE_NO NUMBER PRIMARY KEY,
	MEMBERNO NUMBER NOT NULL,
	MOVIENO NUMBER NOT NULL,
	PAYMENT_NO NUMBER NOT NULL,
	RESERVE_DATE DATE NOT NULL,
	RESERVE_TIME NUMBER NOT NULL,
	RESERVE_SEAT VARCHAR2(10) NOT NULL,
	
	FOREIGN KEY(MEMBERNO) REFERENCES MYMEMBER(MEMBERNO),
	FOREIGN KEY(PAYMENT_NO) REFERENCES PAYMENT(PAYMENT_NO)
)

INSERT INTO RESERVEDSEAT
VALUES(RESERVEDSEAT_SEQ.NEXTVAL, 1, 2, 1, '21-01-11', 11, 'E6')

SELECT * FROM RESERVEDSEAT